Project CRUD
zeterPL/KnowledgeBase pull request #5
Opened 2023-07-05 08:27 UTC by maksimowiczm

2023-07-05 08:31 UTC, tomaszkarelus requested changes
Wrong PR target

2023-07-05 09:05 UTC, tomaszkarelus requested changes
You can't delete migrations because someone could already execute them

2023-07-06 09:25 UTC, tomaszkarelus requested changes

2023-07-06 09:25 UTC, tomaszkarelus commented on KnowledgeBase.Data/Migrations/20230705104918_InitialMingration.cs
> +    public partial class InitialMingration : Migration
It's a mistype but you can leave it as it is

2023-07-06 09:25 UTC, tomaszkarelus commented on KnowledgeBase.Web/Controllers/ProjectController.cs
> +	public IActionResult Create(Project project)
DB Entities should not be a parameters of a api endpoints

2023-07-06 09:25 UTC, tomaszkarelus commented on KnowledgeBase.Web/Controllers/ProjectController.cs
> +		Project project = projectService.Get(id);
This logic should be in service

2023-07-06 10:58 UTC, maksimowiczm commented on KnowledgeBase.Logic/Dto/ProjectDto.cs
> +}
I have no idea where this method should be stored

2023-07-06 18:27 UTC, tomaszkarelus requested changes

2023-07-06 18:27 UTC, tomaszkarelus commented on KnowledgeBase.Logic/Dto/ProjectDto.cs
> +    public Guid Id { get; set; }
It should be nullable because when you create project you don't have ID

2023-07-06 18:27 UTC, tomaszkarelus commented on KnowledgeBase.Logic/Services/ProjectService.cs
> +    public void Remove(ProjectDto projectDto)
There should be no code for removing this entity from the database

2023-07-07 08:20 UTC, merged